### ISSUE TITLE
Dialect flags für Debug-MCU-m$$$ aktualisieren

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-bot#45]
Unter Properties -> C/C++ Build -> Settings finden sich für die Targets

- Debug-MCU-m1284p
- Debug-MCU-m644p
- Debug-MCU-m644

jeweils noch ein veraltetes dialect flag für den GCC C++ Compiler.

Anstelle von -std=gnu++1y sollte (wie bei den anderen Targets schon geschehen) -std=gnu++14 eingetragen werden.

**Comment by tsandmann** [comment]
Für MCU wird absichtlich gnu++1y verwendet, weil einige Linux-Distributionen eine 4.x Version vom avr-gcc ausliefern, die gnu++14 noch nicht kennt. 
Für den ct-Bot-Code ist das auch völlig ausreichend. Bei neueren gcc-Versionen sind gnu++1y und gnu++14  äquivalent.

**Comment by Nightwalker-87** [comment]
Ah ok, ja das macht dann natürlich Sinn. ;-)
Ab welcher version wird c++14 eigentlich vollständig von avr-gcc unterstützt?
Verhält sich das von der Versionierung her so wie bei gcc?
Dann müsste das ja ab v5.0 der Fall sein: [https://en.cppreference.com/w/cpp/compiler_support](url).
Ab ≥ v6.1 wäre es dann das Default-Setting: [https://gcc.gnu.org/projects/cxx-status.html#cxx14](url)

**Comment by tsandmann** [comment]
Ich denke mal, das ist mit der Versionierung wie beim gcc. Viele C++-Features kann der avr-gcc aber eh nicht, mangels stdlib.

**Comment by Nightwalker-87** [comment]
Gut. Ich verschaffe mir zu den Compiler-Versionen gerade einen groben tabellarischen Überblick.
Vorerst gibt es dann hier bei den dialect-flags keinen Handlungsbedarf. Sobald die 3 großen Linux-Basis Distributionen in Ihren stabilen Hauptversionen alle avr-gcc ≥ 6.1 nativ über die Paketquellen unterstützen kann man das aktualisieren - wird aber wahrscheinlich noch eine ganze Weile dauern, da die avr-gcc Entwicklung gegenüber der gcc Entwicklung deutlich hinterher hinkt. Aktuell (Stand 12/2018) sind die da grade erst bei der 5.4er Codebasis angekommen. Ich denke das Ticket kann dann auch als "Resolved" geschlossen werden.
