### ISSUE TITLE
Bug in behaviour_abl.c

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-bot#47]
Der folgende Fehler tritt unter Linux (GCC8) nur beim make-Build und nicht beim Bauen in Eclipse auf. Der Bug trat bislang nicht in Erscheinung, da behaviour_abl.c standardmäßig deaktiviert ist. Vermutung ist, dass hier ein Datentyp oder eine Datenstruktur nicht passt.

`bot-logic/behaviour_abl.c: In function 'load_program':
bot-logic/behaviour_abl.c:258:23: error: invalid operands to binary < (have 'direction_t' {aka 'union <anonymous>'} and 'int')
  } else if (direction _**<**_ 0 && addr >= 512) {

bot-logic/behaviour_abl.c:260:23: error: invalid operands to binary != (have 'direction_t' {aka 'union <anonymous>'} and 'int')
  } else if (direction _**!=**_ 0) {
`
Die Fett-kursiven Operatoren sind in der Ausgabe farblich hervorgehoben.
Hier dürfte es wohl lohnenswert sein mal einen genaueren Blick drauf zu werfen.

**Comment by tsandmann** [comment]
Stimmt, danke für den Hinweise :) Ist in develop jetzt korrigiert.

**Comment by Nightwalker-87** [comment]
Danke, damit ist das Ticket dann auch gelöst.

**Comment by tsandmann** [comment]
Funktioniert ja super, dieses automatische Schließen des Issues, wenn der `Fixes #x` commit gemerged wird... :/
