### ISSUE TITLE
Manuell gesetzte -Wcpp warnings blockieren Travis Builds in bestimmten Konfigurationen

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-bot#49]
Die im Code manuell gesetzten Warnings (# warning: xyz;) [-Wcpp] blockieren erfolgreiche Travis Build Tests, da in deren Config das durchaus nützliche _-Werror_ Flag gesetzt ist.
Gibt es einen schöneren Weg die auf diese Weise gesetzten Hinweise bei der Buildausgabe zu realisieren?

Beispiel:

`In file included from ./include/bot-logic/bot-logic.h:191, from bot-logic/ubasic_call.c:16:
./include/bot-logic/available_behaviours.h:117:2: error:`
`#warning "uBasic-Verhalten benoetigt SDFAT_AVAILABLE (siehe ct-Bot.h)" [-Werror=cpp]`

**Comment by Nightwalker-87** [comment]
Alle Vorkommen im Code:

ct-bot
bot-logic
behaviour_calibrate_sharps.c
305: #warning "Weder RC5_CODE_MUTE noch RC5_CODE_OK vorhanden, bot_calibrate_sharps() funktioniert nicht." 
behaviour_follow_line.c
201: #warning "BEHAVIOUR_AVOID_COL_AVAILABLE sollte aktiv sein fuer FOLLOW_LINE_VERSION == 2" 
behaviour_goto.c
29: #warning "bot_goto_behaviour ist veraltet, besser bot_gotoxy oder drive_distance benutzen!" 
behaviour_line_shortest_way.c
68: #warning "Optimal nur mit Version 3 des Linienfolgers"

include
bot-logic
available_behaviours.h (9 matches)
109: #warning "NN-Fahrverhalten benoetigt BEHAVIOUR_NEURALNET_AVAILABLE (siehe available_behaviours.h)" 
117: #warning "uBasic-Verhalten benoetigt SDFAT_AVAILABLE (siehe ct-Bot.h)" 
128: #warning "drive_area-Verhalten benoetigt POS_STORE_AVAILABLE (siehe ct-Bot.h)" 
133: #warning "Pfadplanungs-Verhalten benoetigt POS_STORE_AVAILABLE (siehe ct-Bot.h)" 
138: #warning "bot_line_shortest_way-Verhalten benoetigt POS_STORE_AVAILABLE (siehe ct-Bot.h)" 
182: #warning "DriveStack-Verhalten benoetigt POS_STORE_AVAILABLE (siehe ct-Bot.h)" 
267: #warning "BEHAVIOUR_CALIBRATE_PID_AVAILABLE benoetigt SPEED_CONTROL_AVAILABLE (siehe ct-Bot.h)" 
272: #warning "GotoPos-Verhalten benoetigt SPEED_CONTROL_AVAILABLE (siehe ct-Bot.h)" 
276: #warning "DriveStack-Verhalten benoetigt SPEED_CONTROL_AVAILABLE (siehe ct-Bot.h)" 
global.h
104: #warning "Big endian byte order detected which isn't fully supported" 
mmc.h
42: #warning "MMC_RAW_WRITE_TEST_AVAILABLE braucht DISPLAY_MMC_INFO (ui/available_screens.h)"

mcu
bootloader.c (4 matches)
65: //#warning "Bitte pruefen, ob der Linker auch mit den Optionen: -Wl,--section-start=.bootloader=0xF800 startet" 
68: //#warning "Bitte pruefen, ob der Linker auch mit den Optionen: -Wl,--section-start=.bootloader=0x1F800 startet" 
74: #warning "Set UART_BAUD to 115200 for bootloader" 
456: #warning "Extension 'ReadFuseLock' enabled" 
twi.c
37: #warning "veraltete Version, besser i2c-Treiber verwenden"

ui
gui.c
93: #warning "RemoteCall-Display geht nur mit aktivem Keypad, Display wurde daher deaktiviert"

ct-Bot.h (2 matches)
230: #warning "POS_STORE_AVAILABLE benoetigt BEHAVIOUR_AVAILABLE" 
235: #warning "SDFAT_AVAILABLE benoetigt OS_AVAILABLE"

**Comment by tsandmann** [comment]
Verstehe ich nicht so ganz... 
  1. Wo wird denn da aktuell irgendetwas blockiert? 
  1. Das sind doch auch Fehler dann, wenn solche inkompatiblen Optionen zusammen konfiguriert sind. Darum sind ja die Warnings eingebaut worden.

**Comment by Nightwalker-87** [comment]
Mir ist das in einer Konfiguration aufgefallen in der alle Optionen aktiviert sind. Eigentlich würde ich hier eher erwarten, dass Meldungen auftreten die darauf hinweisen, dass bestimmte Optionen miteinander im Konflikt stehen (im Sinne von: "benötigt, aber steht im Konflikt mit ... was auch aktiv ist") und nicht, dass bestimmte Defines fehlen (im Sinne von: "benötigt, ist aber nicht aktiv..."), was in diesem Test-Case ja gar nicht der Fall sein kann...

**Comment by tsandmann** [comment]
Kann ich so irgendwie nicht nachvollziehen. 
Hast du ein konkretes Beispiel, wann solche Fehler auftreten? Die o.a. Vorkommen sind ja alles auch tatsächliche Fälle von fehlenden Features.

**Comment by Nightwalker-87** [comment]
hmm, also ich kann dir mal erklären wie du zu der config kommst unter der das auftritt, aber meiner Meinung nach nicht auftreten sollte:
-> aktueller Develop Branch 285d299aa3b41a8732c864fb327a5351a0cc85dd
-> in /include/bot-logic/available_behaviours.h alle #defines für Verhalten einschalten außer bei den drei veralteten Verhalten
-> in ct-bot.h alle #defines für Optionen an
-> in ui/available_screens.h alle Screens aktivieren

Damit kann dann eigentlich keine Funktion mehr "fehlen".

Was mir hier allerdings auch grade auffällt (und was wahrscheinlich die eigentliche Ursache ist, warum das Beschriebene auftritt):
Wenn durch in ct-Bot.h Abhängigkeiten definiert sind wie `#ifndef IR_AVAILABLE
#undef RC5_AVAILABLE
#endif`, welche bestimmte #defines im Code ohne Zutun wieder deaktivieren, dann wäre es aus meiner Sicht zweckmäßig das beim Build auch als Info-Hinweis einzublenden. Aktuell sieht man als Resultat nur die Warnings die bei bestimmten Modulen aufgrund von auf diese Weise entstandenen fehlenden Abhängigkeiten geworfen werden und bei Travis wegen -Werror dann in Fehlern resultieren.

Auch gibt es IMHO bislang keine ausreichende Doku dazu welche Funktion welche Option ein- und ausschaltet.

Am konsequentesten fände ich allerdings wenn es gar nicht erst zu Warnings wie
`235: #warning "SDFAT_AVAILABLE benoetigt OS_AVAILABLE"` kommen kann, indem codeseitig schon erkannt wird, dass für eine aktivierte Funktion nicht alle Abhängigkeiten erfüllt sein können und erstere dann auch wieder deaktiviert wird mit Hinweis.  Im obigen Fall also #undef SDFAT_AVAILABLE.

**Comment by tsandmann** [comment]
Also ich bekomme auch mit dieser Konfiguration (in `ct-Bot.h`, `available_behaviours.h` und `available_screens.h` alle Optionen **an**) keines der von dir genannten Warnings. Lediglich 

> In file included from ./include/log.h:75,
                 from bot-logic/behaviour_abl.c:103:
bot-logic/behaviour_abl.c: In function 'abl_stack_trace':
bot-logic/behaviour_abl.c:875:18: warning: '%-20s' directive output may be truncated writing between 20 and 32 bytes into a region of size 24 [-Wformat-truncation=]
   display_printf("%-20s", abl_i_cache);

was aber ein bekanntes Problem ist und auch keinen Error erzeugt. 

Eine Doku gibt es für [ct-Bot.h](https://github.com/Nightwalker-87/ct-bot-doku/blob/master/_tmp_trac_wiki_export/ctBotH/ctBotH.md) und [available_behaviours.h](https://github.com/Nightwalker-87/ct-bot-doku/blob/master/_tmp_trac_wiki_export/Verhalten/Verhalten.md). Mag nicht ganz vollständig und aktuell sein, aber das kann man ja mal auf den aktuellen Stand bringen. 

> Am konsequentesten fände ich allerdings wenn es gar nicht erst zu Warnings wie
235: #warning "SDFAT_AVAILABLE benoetigt OS_AVAILABLE" kommen kann, indem codeseitig schon erkannt wird, dass für eine aktivierte Funktion nicht alle Abhängigkeiten erfüllt sein können und erstere dann auch wieder deaktiviert wird mit Hinweis. Im obigen Fall also #undef SDFAT_AVAILABLE.

Das ist mit #defines leider nicht wirklich sinnvoll machbar meiner Meinung nach, weil extrem fehleranfällig und sehr schlecht wartbar. Insbesondere, weil die Reihenfolge eine Rolle spielt und zyklische Abhängigkeiten gar nicht möglich sind.

**Comment by Nightwalker-87** [comment]
Achso, ja `-Wpedantic` müsste dafür noch aktiv sein (was standardmäßig aktuell nicht gesetzt ist) ... Das hatte ich vergessen zu erwähnen.
Man könnte aber auch `#pragma message(xyz)` verwenden, dann gibt es mit `-Wpedantic` keine Wechselwirkung. Die Messages ließen sich ja auch ergänzen um den Hinweis, dass wegen einer festgestellten fehlenden Abhängigkeit Funktion _abc_ deaktiviert wurde. Schließlich sind das ja lediglich Hinweise die beim Kompilieren angezeigt werden sollten - der Code regelt das ja dank der aktuellen Implementierung von selbst.
Es ist halt die Frage was hier genau bezweckt werden sollte. Soll der Nutzer nur in Kenntnis gesetzt werden wenn der Code bei Inkompatibitäten selbstständig eingreift, oder soll das Programm dank `-Werror` bei Travis CI Tests in Kombination mit `-Wpedantic` zwingend abbrechen. Bei Letzterem ist aber anzumerken, dass hier der User `-Wpedantic` auch erstmal einschalten müsste...

**Comment by tsandmann** [comment]
`-Wpedantic` ist nicht sinnvoll für den ct-Bot Code, weil das ganze Framework nicht in ISO C sondern in GNU C geschrieben ist. Und wir brauchen die gcc Extensions, damit der Code auch auf dem kleinen ATmega vernünftig läuft.

**Comment by Nightwalker-87** [comment]
Ich hatte jetzt auch nicht vorgesehen `-Wpedantic` dauerhaft einzuschalten, ich hab es aktuell für Testzwecke an um mir die verdeckten Ausgaben anzusehen. Dennoch sind es sind es aber auch nicht viele Punkte wo er wegen ISO C meckern würde. Das war jetzt meinerseits auch gar nicht im Fokus, sondern vielmehr ob es der warnings überhaupt bedarf oder ob das auch reguläre Info-Messages sein können, wenn der Nutzer hier im klassischen Anwendungsfall (mit aktuellen Einstellungen) ohnehin nicht in Kenntnis gesetzt wird.

**Comment by tsandmann** [comment]
Ich wollte damit auch nur darauf hinweisen, dass alles was `-Wpedantic` als Warning ausgibt, für den ct-Bot Code falsch ist, weil wir einen anderen Sprachdialekt verwenden.

Ich verstehe das Problem mit den Warnings durch `#warning` nicht so wirklich: Sie weisen darauf hin, dass die vom Benutzer gewählte Konfiguration Fehler enthält, und deshalb etwas angepasst wurde (was schätzungsweise auch nur 50% der tatsächlich möglichen Inkompatibilitäten fixt, ist leider mit den dummen `#ifdef`s nicht wirklich gut machbar). Das resultierende Programm wird also etwas anderes tun, als das, was der Benutzer (vermutlich) haben wollte - genau in solchen Fällen gibt der Compiler Warnings aus. Also ich denke das passt gut. 
Wieso wird der Nutzer denn im klassischen Anwendungsfalls nicht in Kenntnis gesetzt? Es kommen doch die Warnings...

**Comment by Nightwalker-87** [comment]
> Wieso wird der Nutzer denn im klassischen Anwendungsfalls nicht in Kenntnis gesetzt? Es kommen doch die Warnings...

Ja, stimmt - konnte das grade nochmal ohne `-Wpedantic` sehen, bin da vermutlich mit zwei Test-Branches durcheinandergekommen.

> was schätzungsweise auch nur 50% der tatsächlich möglichen Inkompatibilitäten fixt, ist leider mit den dummen #ifdefs nicht wirklich gut machbar

... was natürlich trotzdem unschön ist :-/

Vllt. lassen wir das Ticket hier auch erstmal ruhen, möglicherweise fällt einem trotz der widrigen Umstände ja irgendwann trotzdem noch was Besseres zu dem Thema ein.
