### ISSUE TITLE
behavior_catch_pillar(): Berechnung der Objektposition ungenau

### ISSUE THREAD

**Issue by tsandmann** [tsandmann/ct-bot#50]
Siehe [Foren-Post](https://www.ctbot.de/viewtopic.php?f=36&t=1217).

**Comment by tsandmann** [comment]
Erster Ansatz zur Verbesserung im Branch [bugfixes/catch_pillar](/tsandmann/ct-bot/tree/bugfixes/catch_pillar). Inwieweit das eine Verbesserung bringt, muss noch getestet werden.

**Comment by tsandmann** [comment]
Die aktualisierte Version des Verhaltens ist jetzt im Branch [develop](../tree/develop) unter [bot-logic/behaviour_catch_pillar.c](../blob/develop/bot-logic/behaviour_catch_pillar.c) zu finden. 

Das Verhalten hat einen Parameter (`uint8_t mode`) zur Auswahl des Modus zur Berechnung der Objektposition bekommen:
- 0: Drehwinkel
- 1: linker Distanzsensor
- 2: rechter Distanzsensor
- 3: Durchschnitt linker und rechter Distanzsensor

Ausführliche Tests auf realer Hardware stehen allerdings noch aus.

**Comment by tsandmann** [comment]
Ein paar weitere Tests ergaben, dass das erfolgreiche Einfangen des Objekts sehr stark von Genauigkeit der Distanzsensoren abhängt. Da die Sensoren einen Öffnungswinkel von ca. 3 Grad haben, ist eine exakte Bestimmung der Objektposition in verschiedenen Umgebungen schwierig. 
Zum Feintuning gibt es einen weiteren Parameter [`BEAM_WIDTH `](../blob/develop/bot-logic/behaviour_catch_pillar.c#L37) im Code, mit dem sich dem Einfluss der Sensorunschärfe entgegen wirken lässt. Der Wert hängt auch von der Oberfläche (Farbe und Material) des einzufangenden Objekts ab und muss daher experimentell ermittelt werden. Weißes Papier hat sich als gut erkennbar für die Distanzsensoren erwiesen, schwarzer Kunststoff als eher ungenau.
Weiteres Feedback erwünscht, wie gut das aktualisierte Verhalten jetzt funktioniert. 🙂

**Comment by r4dh4l** [comment]
> Weiteres Feedback erwünscht, wie gut das aktualisierte Verhalten jetzt funktioniert. slightly_smiling_face

:1st_place_medal: 

Danke vielmals, teste ich bei nächster Gelegenheit! :)

**Comment by tsandmann** [comment]
Ich denke das ursprüngliche Problem ist mit dem Update vom 18.9.2020 gelöst, hat bei mir mit dem Eier-Such-Verhalten jedenfalls ganz gut funktioniert. Daher schließe ich das Ticket mal. 
Wenn es doch noch Probleme geben sollte, bitte melden.
